function importModule() {
  return {
    type: "hero",
    id: "Akali",
    title: "离群之刺",
    name: "阿卡丽",
    avatar: "Akali.png",
    skins: [
      { name: "default", skin: "Akali_0.jpg" },
      { name: "蜂刺 阿卡丽", skin: "Akali_1.jpg" },
      { name: "奈落之炎 阿卡丽", skin: "Akali_2.jpg" },
      { name: "足球宝贝 阿卡丽", skin: "Akali_3.jpg" },
      { name: "实习护士 阿卡丽", skin: "Akali_4.jpg" },
      { name: "腥红之月 鬼武姬 阿卡丽", skin: "Akali_5.jpg" },
      { name: "银色之牙 阿卡丽", skin: "Akali_6.jpg" },
      { name: "铁血女忍 阿卡丽", skin: "Akali_7.jpg" },
      { name: "刺身之拳 阿卡丽", skin: "Akali_8.jpg" },
      { name: "K/DA 阿卡丽", skin: "Akali_9.jpg" },
      { name: "至臻 K/DA 阿卡丽", skin: "Akali_13.jpg" },
      { name: "源计划：暗影 阿卡丽", skin: "Akali_14.jpg" },
      { name: "真实伤害 阿卡丽", skin: "Akali_15.jpg" },
      { name: "K/DA ALL OUT 阿卡丽", skin: "Akali_32.jpg" },
      { name: "地下都市 梦魇 阿卡丽", skin: "Akali_50.jpg" },
      { name: "至臻 K/DA 阿卡丽 (2022)", skin: "Akali_60.jpg" },
      { name: "星之守护者 阿卡丽", skin: "Akali_61.jpg" },
      { name: "DRX 阿卡丽", skin: "Akali_68.jpg" },
      { name: "魔女 阿卡丽", skin: "Akali_70.jpg" },
      { name: "至臻 魔女 阿卡丽", skin: "Akali_71.jpg" },
      { name: "至高天 阿卡丽", skin: "Akali_82.jpg" },
    ],
    spells: [
      {
        id: "AkaliP",
        name: "我流忍法！潜龙印",
        icon: "AkaliP.png",
        description: "",
      },
      {
        id: "AkaliQ",
        name: "我流奥义！寒影",
        icon: "AkaliQ.png",
        description: "",
      },
      {
        id: "AkaliW",
        name: "我流奥义！霞阵",
        icon: "AkaliW.png",
        description: "",
      },
      {
        id: "AkaliE",
        name: "我流奥义！隼舞",
        icon: "AkaliE.png",
        description: "",
      },
      {
        id: "AkaliR",
        name: "我流秘奥义！表里杀缭乱",
        icon: "AkaliR.png",
        description: "",
      },
    ],
    effects: {
      AkaliP: null,
      AkaliQ: null,
      AkaliW: null,
      AkaliE: null,
      AkaliR: null,
    },
  };
}
export { importModule };
