function importModule() {
  return {
    type: "hero",
    id: "Ashe",
    title: "寒冰射手",
    name: "艾希",
    avatar: "Ashe.png",
    skins: [
      { name: "default", skin: "Ashe_0.jpg" },
      { name: "极地女神 艾希", skin: "Ashe_1.jpg" },
      { name: "丛林侠盗 艾希", skin: "Ashe_2.jpg" },
      { name: "勇敢的心 艾希", skin: "Ashe_3.jpg" },
      { name: "女皇 艾希", skin: "Ashe_4.jpg" },
      { name: "紫晶射手 艾希", skin: "Ashe_5.jpg" },
      { name: "觅心女王 艾希", skin: "Ashe_6.jpg" },
      { name: "黑暗骑士 艾希", skin: "Ashe_7.jpg" },
      { name: "源计划：联合 艾希", skin: "Ashe_8.jpg" },
      { name: "冠军之箭 艾希", skin: "Ashe_9.jpg" },
      { name: "御星魔矢 艾希", skin: "Ashe_11.jpg" },
      { name: "西部天使 艾希", skin: "Ashe_17.jpg" },
      { name: "神龙尊者 苍龙艾希", skin: "Ashe_23.jpg" },
      { name: "魔女 艾希", skin: "Ashe_32.jpg" },
      { name: "海之歌 艾希", skin: "Ashe_43.jpg" },
      { name: "春晖神女 艾希", skin: "Ashe_52.jpg" },
      { name: "DRX 艾希", skin: "Ashe_63.jpg" },
      { name: "水晶圣骑 艾希", skin: "Ashe_65.jpg" },
      { name: "地狱火 艾希", skin: "Ashe_67.jpg" },
    ],
    spells: [
      { id: "AsheP", name: "冰霜射击", icon: "AsheP.png", description: "" },
      { id: "AsheQ", name: "射手的专注", icon: "AsheQ.png", description: "" },
      { id: "AsheW", name: "万箭齐发", icon: "AsheW.png", description: "" },
      { id: "AsheE", name: "鹰击长空", icon: "AsheE.png", description: "" },
      { id: "AsheR", name: "魔法水晶箭", icon: "AsheR.png", description: "" },
    ],
    effects: {
      AsheP: null,
      AsheQ: null,
      AsheW: null,
      AsheE: null,
      AsheR: null,
    },
  };
}
export { importModule };
