function importModule() {
  return {
    type: "hero",
    id: "MissFortune",
    title: "赏金猎人",
    name: "厄运小姐",
    avatar: "MissFortune.png",
    skins: [
      { name: "default", skin: "MissFortune_0.jpg" },
      { name: "西部牛仔 厄运小姐", skin: "MissFortune_1.jpg" },
      { name: "法国皇室 厄运小姐", skin: "MissFortune_2.jpg" },
      { name: "特工狂花 厄运小姐", skin: "MissFortune_3.jpg" },
      { name: "圣诞糖果棒 厄运小姐", skin: "MissFortune_4.jpg" },
      { name: "荒野女警 厄运小姐", skin: "MissFortune_5.jpg" },
      { name: "黑帮狂花 厄运小姐", skin: "MissFortune_6.jpg" },
      { name: "电玩女神 厄运小姐", skin: "MissFortune_7.jpg" },
      { name: "女船长 厄运小姐", skin: "MissFortune_8.jpg" },
      { name: "泳池派对 厄运小姐", skin: "MissFortune_9.jpg" },
      { name: "星之守护者 厄运小姐", skin: "MissFortune_15.jpg" },
      { name: "武装战姬 厄运小姐", skin: "MissFortune_16.jpg" },
      { name: "睡衣守护者 厄运小姐", skin: "MissFortune_17.jpg" },
      { name: "魅惑女巫 厄运小姐", skin: "MissFortune_18.jpg" },
      { name: "至臻 魅惑女巫 厄运小姐", skin: "MissFortune_20.jpg" },
      { name: "破败军团 厄运小姐", skin: "MissFortune_21.jpg" },
      { name: "幻灵战斗队长 厄运小姐", skin: "MissFortune_31.jpg" },
      { name: "幻灵战斗兔司令 厄运小姐", skin: "MissFortune_32.jpg" },
      { name: "至臻 魅惑女巫 厄运小姐 (2022)", skin: "MissFortune_33.jpg" },
      { name: "绝息圣堂 厄运小姐", skin: "MissFortune_40.jpg" },
      { name: "至臻 绝息圣堂 厄运小姐", skin: "MissFortune_41.jpg" },
      { name: "青花瓷 厄运小姐", skin: "MissFortune_50.jpg" },
      { name: "女帝 厄运小姐", skin: "MissFortune_60.jpg" },
    ],
    spells: [
      {
        id: "MissFortuneP",
        name: "厄运的眷顾",
        icon: "MissFortuneP.png",
        description: "",
      },
      {
        id: "MissFortuneQ",
        name: "一箭双雕",
        icon: "MissFortuneQ.png",
        description: "",
      },
      {
        id: "MissFortuneW",
        name: "大步流星",
        icon: "MissFortuneW.png",
        description: "",
      },
      {
        id: "MissFortuneE",
        name: "枪林弹雨",
        icon: "MissFortuneE.png",
        description: "",
      },
      {
        id: "MissFortuneR",
        name: "弹幕时间",
        icon: "MissFortuneR.png",
        description: "",
      },
    ],
    effects: {
      MissFortuneP: null,
      MissFortuneQ: null,
      MissFortuneW: null,
      MissFortuneE: null,
      MissFortuneR: null,
    },
  };
}
export { importModule };
